# Generated by Django 3.1.7 on 2021-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0002_payment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('groceries', 'Groceries'), ('shopping', 'Shopping'), ('gym', 'Gym'), ('phone', 'Phone'), ('freetime', 'Freetime'), ('other', 'Other')], default='Other', max_length=25),
        ),
    ]
